# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0005_auto_20160521_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='car_name',
        ),
        migrations.AddField(
            model_name='deal',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crms.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
