# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0007_deal_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alipay',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drive_license',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
