# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0009_auto_20160521_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('manual', models.BooleanField()),
                ('img', models.ImageField(null=True, upload_to='')),
                ('displacement', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='car_name',
            new_name='realname',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='time',
        ),
        migrations.AddField(
            model_name='deal',
            name='fetch_date',
            field=models.DateTimeField(null=True, verbose_name='fetch date'),
        ),
        migrations.AddField(
            model_name='deal',
            name='return_date',
            field=models.DateTimeField(null=True, verbose_name='return date'),
        ),
        migrations.AddField(
            model_name='offer',
            name='fetch_date',
            field=models.DateTimeField(null=True, verbose_name='fetch date'),
        ),
        migrations.AddField(
            model_name='offer',
            name='return_date',
            field=models.DateTimeField(null=True, verbose_name='return date'),
        ),
        migrations.AddField(
            model_name='offer',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crms.Car'),
        ),
    ]
