# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0013_auto_20160522_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='owner',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('丰田', '丰田'), ('大众', '大众'), ('本田', '本田')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('凯美瑞', '凯美瑞'), ('卡罗拉', '卡罗拉'), ('锐志', '锐志')], max_length=50, null=True),
        ),
    ]
