# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0014_auto_20160522_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deal',
            name='offer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crms.Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='crms.Car'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alipay',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drive_license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_identity',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
