# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0015_auto_20160523_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crms.Offer'),
        ),
    ]
