# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0017_auto_20160523_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='displacement',
        ),
    ]
