# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crms', '0003_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('drive_license', models.CharField(max_length=50)),
                ('social_identity', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='drive_license',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
