# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0008_auto_20160521_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
