# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0016_auto_20160523_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='img',
        ),
        migrations.RemoveField(
            model_name='car',
            name='manual',
        ),
        migrations.AddField(
            model_name='car',
            name='gear_box',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20, null=True),
        ),
    ]
