# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0019_auto_20160523_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='car',
            name='displacement',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('丰田', '丰田'), ('大众', '大众'), ('本田', '本田')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_box',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('凯美瑞', '凯美瑞'), ('卡罗拉', '卡罗拉'), ('锐志', '锐志')], max_length=50, null=True),
        ),
    ]
